package client.GUI.professors;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import client.GUI.*;
import client.Client;
import shared.model.PanelName;
import shared.model.users.UserRole;
import shared.util.Config;

import javax.swing.*;
import java.awt.*;
import java.io.File;

/**
 *
 * @author HP
 */
public class ProfessorPanel extends javax.swing.JPanel {

  MainFrame mainFrame;
  Client client;

  /**
   * Creates new form ProfessorPanel
   */
  public ProfessorPanel(MainFrame mainFrame, JPanel panel, Client client) {
    this.client = client;
    this.add(panel);
    this.mainFrame = mainFrame;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    registrationMattersPanel = new javax.swing.JPanel();
    coursesListButton = new javax.swing.JButton();
    professorsListButton = new javax.swing.JButton();
    recordAffairsButton = new javax.swing.JButton();
    recordAffairsPanel = new javax.swing.JPanel();
    temporaryScoreButton = new javax.swing.JButton();
    educationalServicesPanel = new javax.swing.JPanel();
    weeklyScheduleButton = new javax.swing.JButton();
    examListButton = new javax.swing.JButton();
    requestsButton = new javax.swing.JButton();
    timeLabel = new javax.swing.JLabel();
    currentTimeLabel = new javax.swing.JLabel();
    logoutButton = new javax.swing.JButton();
    emailLabel = new javax.swing.JLabel();
    registrationMattersButton = new javax.swing.JButton();
    educationalServicesButton = new javax.swing.JButton();
    nameLabel = new javax.swing.JLabel();
    mainPageButton = new javax.swing.JButton();
    profileButton = new javax.swing.JButton();
    imgLabel = new javax.swing.JLabel();

    registrationMattersPanel.setBackground(new java.awt.Color(100, 100, 240));
    registrationMattersPanel.setVisible(false);

    coursesListButton.setText(getConfig().getProperty(String.class, "coursesListButtonText"));
    coursesListButton.addActionListener(this::coursesListButtonActionPerformed);

    professorsListButton.setText(getConfig().getProperty(String.class, "professorsListButtonText"));
    professorsListButton.addActionListener(this::professorsListButtonActionPerformed);

    javax.swing.GroupLayout registrationMattersPanelLayout = new javax.swing.GroupLayout(registrationMattersPanel);
    registrationMattersPanel.setLayout(registrationMattersPanelLayout);
    registrationMattersPanelLayout.setHorizontalGroup(
            registrationMattersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrationMattersPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(registrationMattersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationMattersPanelLayout.createSequentialGroup()
                                            .addComponent(coursesListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(professorsListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap())
    );
    registrationMattersPanelLayout.setVerticalGroup(
            registrationMattersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrationMattersPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(coursesListButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(professorsListButton)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    recordAffairsButton.setText(getConfig().getProperty(String.class, "recordAffairsButtonText"));
    recordAffairsButton.addActionListener(this::recordAffairsButtonActionPerformed);

    recordAffairsPanel.setBackground(new java.awt.Color(100, 100, 240));
    recordAffairsPanel.setVisible(false);

    temporaryScoreButton.setText(getConfig().getProperty(String.class, "temporaryScoreButtonText"));
    temporaryScoreButton.addActionListener(this::temporaryScoreActionPerformed);

    javax.swing.GroupLayout recordAffairsPanelLayout = new javax.swing.GroupLayout(recordAffairsPanel);
    recordAffairsPanel.setLayout(recordAffairsPanelLayout);
    recordAffairsPanelLayout.setHorizontalGroup(
            recordAffairsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recordAffairsPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(temporaryScoreButton, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addContainerGap())
    );
    recordAffairsPanelLayout.setVerticalGroup(
            recordAffairsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recordAffairsPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(temporaryScoreButton)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    educationalServicesPanel.setBackground(new java.awt.Color(100, 100, 240));
    educationalServicesPanel.setVisible(false);

    weeklyScheduleButton.setText(getConfig().getProperty(String.class, "weeklyScheduleButtonText"));
    weeklyScheduleButton.addActionListener(this::weeklyScheduleButtonActionPerformed);

    examListButton.setText(getConfig().getProperty(String.class, "examListButtonText"));
    examListButton.addActionListener(this::examListButtonActionPerformed);

    requestsButton.setText(getConfig().getProperty(String.class, "requestsButtonText"));
    requestsButton.addActionListener(this::requestButtonActionPerformed);

    javax.swing.GroupLayout educationalServicesPanelLayout = new javax.swing.GroupLayout(educationalServicesPanel);
    educationalServicesPanel.setLayout(educationalServicesPanelLayout);
    educationalServicesPanelLayout.setHorizontalGroup(
            educationalServicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, educationalServicesPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(educationalServicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(requestsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(examListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(weeklyScheduleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                            .addContainerGap())
    );
    educationalServicesPanelLayout.setVerticalGroup(
            educationalServicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(educationalServicesPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(weeklyScheduleButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(examListButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(requestsButton)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    timeLabel.setBackground(new java.awt.Color(200, 200, 200));
    timeLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18));
    timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    timeLabel.setOpaque(true);

    currentTimeLabel.setBackground(new java.awt.Color(200, 200, 200));
    currentTimeLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 17)); // NOI18N
    currentTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    currentTimeLabel.setOpaque(true);

    logoutButton.setText(getConfig().getProperty(String.class, "logoutButtonText"));
    logoutButton.addActionListener(this::logoutButtonActionPerformed);

    emailLabel.setBackground(new java.awt.Color(200, 200, 200));
    emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    emailLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18));
    emailLabel.setOpaque(true);

    registrationMattersButton.setText(getConfig().getProperty(String.class, "registrationMattersButtonText"));
    registrationMattersButton.addActionListener(this::registrationMattersButtonActionPerformed);

    educationalServicesButton.setText(getConfig().getProperty(String.class, "educationalServicesButtonText"));
    educationalServicesButton.addActionListener(this::educationalServicesButtonActionPerformed);

    nameLabel.setBackground(new java.awt.Color(200, 200, 200));
    nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    nameLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18));
    nameLabel.setOpaque(true);

    imgLabel.setText("ax");

    mainPageButton.setText(getConfig().getProperty(String.class, "mainPageButtonText"));
    mainPageButton.addActionListener(this::mainPageButtonActionPerformed);

    profileButton.setText(getConfig().getProperty(String.class, "profileButtonText"));
    profileButton.addActionListener(this::profileButtonActionPerformed);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(mainPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(registrationMattersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(registrationMattersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(educationalServicesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(educationalServicesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(recordAffairsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(recordAffairsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(50, 50, 50)
                            .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(currentTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imgLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(50, 50, 50))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mainPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(recordAffairsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(registrationMattersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(educationalServicesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(educationalServicesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(recordAffairsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(registrationMattersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addContainerGap(91, Short.MAX_VALUE)
                                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(63, 63, 63))
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(currentTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(611, 611, 611))
    );
  }// </editor-fold>

  private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
    client.logout();
  }

  private void mainPageButtonActionPerformed(java.awt.event.ActionEvent evt) {
    client.changePanel(PanelName.PROFESSOR_PANEL, null);
  }

  private void registrationMattersButtonActionPerformed(java.awt.event.ActionEvent evt) {
    registrationMattersPanel.setVisible(!registrationMattersPanel.isVisible());
    educationalServicesPanel.setVisible(false);
    recordAffairsPanel.setVisible(false);
  }

  private void educationalServicesButtonActionPerformed(java.awt.event.ActionEvent evt) {
    registrationMattersPanel.setVisible(false);
    educationalServicesPanel.setVisible(!educationalServicesPanel.isVisible());
    recordAffairsPanel.setVisible(false);
  }

  private void recordAffairsButtonActionPerformed(java.awt.event.ActionEvent evt) {
    registrationMattersPanel.setVisible(false);
    educationalServicesPanel.setVisible(false);
    recordAffairsPanel.setVisible(!recordAffairsPanel.isVisible());
  }

  private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {
    client.changePanel(PanelName.PROFESSOR_PROFILE_PANEL, UserRole.Professor);
  }

  private void coursesListButtonActionPerformed(java.awt.event.ActionEvent evt) {
    client.changeToCoursesListPanel(UserRole.Professor, getConfig().getProperty(String.class, "comboBoxDefault"),
            "", getConfig().getProperty(String.class, "comboBoxDefault"));
  }

  private void professorsListButtonActionPerformed(java.awt.event.ActionEvent evt) {
    client.changeToProfessorsListPanel(UserRole.Professor, getConfig().getProperty(String.class, "comboBoxDefault"),
            "", getConfig().getProperty(String.class, "comboBoxDefault"));
  }

  private void weeklyScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {
    client.changePanel(PanelName.WEEKLY_SCHEDULE_PANEL, UserRole.Professor);
  }

  private void examListButtonActionPerformed(java.awt.event.ActionEvent evt) {
    client.changePanel(PanelName.EXAM_LIST_PANEL, UserRole.Professor);
  }

  private void requestButtonActionPerformed(java.awt.event.ActionEvent evt) {
    client.changePanel(PanelName.RECOMMENDATION_LIST_PANEL, UserRole.Professor);
  }

  private void temporaryScoreActionPerformed(java.awt.event.ActionEvent evt) {
    client.changePanel(PanelName.PROFESSORS_COURSE_LIST, UserRole.Professor);
  }

  public void update(String  id, String lastLogin, String email, String name, String currentTime) {
    File file = new File(String.format(getConfig().getProperty(String.class, "imgFilePath"), id));
    imgLabel.setIcon(new ImageIcon(String.format(getConfig().getProperty(String.class, "imgFilePath"), file.exists() ? id : "default")));

    nameLabel.setText(String.format(getConfig().getProperty(String.class, "nameLabelText"), (name==null || name.equals("")) ? "-" : name));
    timeLabel.setText(String.format(getConfig().getProperty(String.class, "timeLabelText"), (lastLogin==null || lastLogin.equals("")) ? "-" : lastLogin));
    emailLabel.setText(String.format(getConfig().getProperty(String.class, "emailLabelText"), (email==null || email.equals("")) ? "-" : email));
    currentTimeLabel.setText(String.format(getConfig().getProperty(String.class, "currentTimeLabelText"), currentTime));
  }

  private Config getConfig() {
    return Config.getConfig(Config.getMainConfig().getProperty(String.class, "professorConfig"));
  }

  // Variables declaration - do not modify
  private javax.swing.JButton educationalServicesButton;
  private javax.swing.JPanel educationalServicesPanel;
  private javax.swing.JLabel emailLabel;
  private javax.swing.JLabel imgLabel;
  private javax.swing.JButton requestsButton;
  private javax.swing.JButton temporaryScoreButton;
  private javax.swing.JButton coursesListButton;
  private javax.swing.JButton professorsListButton;
  private javax.swing.JButton weeklyScheduleButton;
  private javax.swing.JButton examListButton;
  private javax.swing.JButton logoutButton;
  private javax.swing.JButton mainPageButton;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JButton profileButton;
  private javax.swing.JButton recordAffairsButton;
  private javax.swing.JPanel recordAffairsPanel;
  private javax.swing.JButton registrationMattersButton;
  private javax.swing.JPanel registrationMattersPanel;
  private javax.swing.JLabel timeLabel;
  private javax.swing.JLabel currentTimeLabel;
  // End of variables declaration
}
