package client.GUI;

import client.Client;
import shared.util.Config;

import javax.swing.*;
import java.awt.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class ChangePasswordPanel extends javax.swing.JPanel {
  MainFrame mainFrame;
  Client client;

  /**
   * Creates new form changePasswordPanel
   */
  public ChangePasswordPanel(MainFrame mainFrame, Client client) {
    this.client = client;
    this.mainFrame = mainFrame;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    alertLabel = new JLabel();
    currentPassLabel = new JLabel();
    newPassLabel = new JLabel();
    verifyPassLabel = new JLabel();
    changeButton = new JButton();
    currentPassField = new JPasswordField();
    newPassField = new JPasswordField();
    verifyPassField = new JPasswordField();
    currentPassCheck = new JCheckBox();
    newPassCheck = new JCheckBox();
    verifyPassCheck = new JCheckBox();

    alertLabel.setFont(new Font("Tahoma", Font.PLAIN, 36)); // NOI18N
    alertLabel.setForeground(new Color(255, 0, 0));
    alertLabel.setHorizontalAlignment(SwingConstants.CENTER);
    alertLabel.setText(getConfig().getProperty(String.class, "alertLabelText"));

    currentPassLabel.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    currentPassLabel.setHorizontalAlignment(SwingConstants.CENTER);
    currentPassLabel.setText(getConfig().getProperty(String.class, "currentPassLabelText"));

    newPassLabel.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    newPassLabel.setHorizontalAlignment(SwingConstants.CENTER);
    newPassLabel.setText(getConfig().getProperty(String.class, "newPassLabelText"));

    verifyPassLabel.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    verifyPassLabel.setHorizontalAlignment(SwingConstants.CENTER);
    verifyPassLabel.setText(getConfig().getProperty(String.class, "verifyPassLabelText"));

    changeButton.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    changeButton.setText(getConfig().getProperty(String.class, "changeButtonText"));
    changeButton.addActionListener(this::changeButtonActionPerformed);

    currentPassField.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    currentPassField.setHorizontalAlignment(JTextField.CENTER);
    currentPassField.setEchoChar('*');

    newPassField.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    newPassField.setHorizontalAlignment(JTextField.CENTER);
    newPassField.setEchoChar('*');

    verifyPassField.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    verifyPassField.setHorizontalAlignment(JTextField.CENTER);
    verifyPassField.setEchoChar('*');

    currentPassCheck.addActionListener(this::currentPassCheckActionPerformed);

    newPassCheck.addActionListener(this::newPassCheckActionPerformed);

    verifyPassCheck.addActionListener(this::verifyPassCheckActionPerformed);

    GroupLayout layout = new GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(718, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(alertLabel, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 599, GroupLayout.PREFERRED_SIZE)
                                            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(changeButton, GroupLayout.PREFERRED_SIZE, 158, GroupLayout.PREFERRED_SIZE)
                                                    .addGap(27, 27, 27)))
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(88, 88, 88)
                                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                    .addComponent(verifyPassLabel, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(newPassLabel, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(currentPassLabel, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE))
                                            .addGap(53, 53, 53)
                                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(currentPassField)
                                                    .addComponent(newPassField)
                                                    .addComponent(verifyPassField, GroupLayout.PREFERRED_SIZE, 183, GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                    .addComponent(currentPassCheck)
                                                    .addComponent(newPassCheck)
                                                    .addComponent(verifyPassCheck))))
                            .addGap(633, 633, 633))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addComponent(alertLabel, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
                            .addGap(135, 135, 135)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(currentPassLabel, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currentPassField, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currentPassCheck))
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(newPassLabel, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                                            .addComponent(newPassField, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE))
                                    .addComponent(newPassCheck))
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(verifyPassLabel, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                                            .addComponent(verifyPassField, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE))
                                    .addComponent(verifyPassCheck))
                            .addGap(74, 74, 74)
                            .addComponent(changeButton, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(279, Short.MAX_VALUE))
    );
  }// </editor-fold>

  private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {
    if (newPassField.getText().equals("")) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "emptyPassErrorMessage"));
      client.changePasswordPanelCLI();
      return;
    }

    if (!newPassField.getText().equals(verifyPassField.getText())) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "notMatchErrorMessage"));
      client.changePasswordPanelCLI();
      return;
    }

    if (currentPassField.getText().equals(newPassField.getText())) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "differErrorMessage"));
      client.changePasswordPanelCLI();
      return;
    }

    client.changePassword(currentPassField.getText(), newPassField.getText());
  }

  private void currentPassCheckActionPerformed(java.awt.event.ActionEvent evt) {
    if (currentPassCheck.isSelected()) {
      currentPassField.setEchoChar((char) 0);
    } else {
      currentPassField.setEchoChar('*');
    }
  }

  private void newPassCheckActionPerformed(java.awt.event.ActionEvent evt) {
    if (newPassCheck.isSelected()) {
      newPassField.setEchoChar((char) 0);
    } else {
      newPassField.setEchoChar('*');
    }
  }

  private void verifyPassCheckActionPerformed(java.awt.event.ActionEvent evt) {
    if (verifyPassCheck.isSelected()) {
      verifyPassField.setEchoChar((char) 0);
    } else {
      verifyPassField.setEchoChar('*');
    }
  }

  private Config getConfig() {
    return Config.getConfig(Config.getMainConfig().getProperty(String.class, "GUIConfig"));
  }

  // Variables declaration - do not modify
  private javax.swing.JLabel alertLabel;
  private javax.swing.JButton changeButton;
  private javax.swing.JCheckBox currentPassCheck;
  private javax.swing.JPasswordField currentPassField;
  private javax.swing.JLabel currentPassLabel;
  private javax.swing.JCheckBox newPassCheck;
  private javax.swing.JPasswordField newPassField;
  private javax.swing.JLabel newPassLabel;
  private javax.swing.JCheckBox verifyPassCheck;
  private javax.swing.JPasswordField verifyPassField;
  private javax.swing.JLabel verifyPassLabel;
  // End of variables declaration
}
