package client.GUI.admin;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import client.Client;
import client.GUI.MainFrame;
import shared.model.PanelName;
import shared.model.users.UserRole;
import shared.util.Config;

import javax.swing.*;
import java.awt.*;
import java.io.File;

/**
 *
 * @author HP
 */
public class AdminPanel extends javax.swing.JPanel {
  MainFrame mainFrame;
  Client client;

  /**
   * Creates new form AdminPanel
   */
  public AdminPanel(MainFrame mainFrame, JPanel jPanel, Client client) {
    this.client = client;
    this.mainFrame = mainFrame;
    this.add(jPanel);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    emailLabel = new javax.swing.JLabel();
    timeLabel = new javax.swing.JLabel();
    imgLabel = new javax.swing.JLabel();
    logoutButton = new javax.swing.JButton();
    currentTimeLabel = new javax.swing.JLabel();
    nameLabel = new javax.swing.JLabel();
    chatsButton = new javax.swing.JButton();
    offlineLabel = new javax.swing.JLabel();
    refreshButton = new javax.swing.JButton();

    emailLabel.setBackground(new java.awt.Color(200, 200, 200));
    emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    emailLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18));
    emailLabel.setOpaque(true);

    timeLabel.setBackground(new java.awt.Color(200, 200, 200));
    timeLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    timeLabel.setOpaque(true);

    imgLabel.setText("ax");

    logoutButton.setText(getConfig().getProperty(String.class, "logoutButtonText"));
    logoutButton.addActionListener(this::logoutButtonActionPerformed);

    currentTimeLabel.setBackground(new java.awt.Color(200, 200, 200));
    currentTimeLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    currentTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    currentTimeLabel.setOpaque(true);

    nameLabel.setBackground(new java.awt.Color(200, 200, 200));
    nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    nameLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18));
    nameLabel.setOpaque(true);

    chatsButton.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 20)); // NOI18N
    chatsButton.setText(getConfig().getProperty(String.class, "chatsButtonText"));
    chatsButton.addActionListener(this::chatsButtonActionPerformed);

    offlineLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 22)); // NOI18N
    offlineLabel.setForeground(new java.awt.Color(255, 0, 51));
    offlineLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    offlineLabel.setText("");

    refreshButton.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 20)); // NOI18N
    refreshButton.setText(getConfig().getProperty(String.class, "refreshButtonText"));
    refreshButton.addActionListener(this::refreshButtonActionPerformed);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(353, 353, 353)
                            .addComponent(chatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(280, 280, 280)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                            .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(currentTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(33, 33, 33)
                                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(offlineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(142, 142, 142))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(currentTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                            .addComponent(offlineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(204, 204, 204))
    );
  }// </editor-fold>

  private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
    client.logout();
  }

  private void chatsButtonActionPerformed(java.awt.event.ActionEvent evt) {
    client.changePanel(PanelName.MESSENGER_PANEL, UserRole.ADMIN);
  }

  private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {
    client.refresh();
  }

  public void update(String id, String lastLogin, String email, String name, String currentTime) {
    if (client.isConnected()) {
      offlineLabel.setText("");
      refreshButton.setVisible(false);
    } else {
      offlineLabel.setText(getConfig().getProperty(String.class, "offlineLabelText"));
      refreshButton.setVisible(true);
    }
    File file = new File(String.format(getConfig().getProperty(String.class, "imgFilePath"), id));
    imgLabel.setIcon(new ImageIcon(String.format(getConfig().getProperty(String.class, "imgFilePath"), file.exists() ? id : "default")));

    nameLabel.setText(String.format(getConfig().getProperty(String.class, "nameLabelText"), (name==null || name.equals("")) ? "-" : name));
    timeLabel.setText(String.format(getConfig().getProperty(String.class, "timeLabelText"), (lastLogin==null || lastLogin.equals("")) ? "-" : lastLogin));
    emailLabel.setText(String.format(getConfig().getProperty(String.class, "emailLabelText"), (email==null || email.equals("")) ? "-" : email));
    currentTimeLabel.setText(String.format(getConfig().getProperty(String.class, "currentTimeLabelText"), currentTime));
  }

  private Config getConfig() {
    return Config.getConfig(Config.getMainConfig().getProperty(String.class, "adminConfig"));
  }

  // Variables declaration - do not modify
  private javax.swing.JButton chatsButton;
  private javax.swing.JLabel currentTimeLabel;
  private javax.swing.JLabel emailLabel;
  private javax.swing.JLabel imgLabel;
  private javax.swing.JButton logoutButton;
  private javax.swing.JLabel offlineLabel;
  private javax.swing.JButton refreshButton;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JLabel timeLabel;
  // End of variables declaration
}
