package GUI.professors.eduAssistant;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import GUI.MainFrame;
import client.Client;
import shared.model.*;

import java.awt.*;

/**
 *
 * @author HP
 */
public class CourseSummaryPanel extends javax.swing.JPanel {
  MainFrame mainFrame;
  Client client;

  /**
   * Creates new form CourseSummaryPanel
   */
  public CourseSummaryPanel(MainFrame mainFrame, Client client) {
    this.client = client;
    this.mainFrame = mainFrame;
    setBounds(200, 270, 1100, 700);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    courseField = new javax.swing.JTextField();
    courseLabel = new javax.swing.JLabel();
    facultyLabel = new javax.swing.JLabel();
    gradeLabel = new javax.swing.JLabel();
    nameLabel = new javax.swing.JLabel();
    idLabel = new javax.swing.JLabel();
    professorLabel = new javax.swing.JLabel();
    searchButton = new javax.swing.JButton();
    averageLabel = new javax.swing.JLabel();
    studentLabel = new javax.swing.JLabel();
    passStudentLabel = new javax.swing.JLabel();
    failStudentLabel = new javax.swing.JLabel();
    passAverageLabel = new javax.swing.JLabel();
    averageAnswerLabel = new javax.swing.JLabel();
    studentAnswerLabel = new javax.swing.JLabel();
    passStudentAnswerLabel = new javax.swing.JLabel();
    failStudentAnswerLabel = new javax.swing.JLabel();
    passAverageAnswerLabel = new javax.swing.JLabel();

    courseField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    courseLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    courseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    courseLabel.setText("course id:");

    facultyLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    facultyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    facultyLabel.setText("faculty:");

    gradeLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    gradeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    gradeLabel.setText("grade:");

    nameLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    nameLabel.setText("name:");

    idLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    idLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    idLabel.setText("id:");

    professorLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    professorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    professorLabel.setText("professor:");

    searchButton.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    searchButton.setText("search");
    searchButton.addActionListener(this::searchButtonActionPerformed);

    averageLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    averageLabel.setText("average score:");

    studentLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    studentLabel.setText("count of students:");

    passStudentLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    passStudentLabel.setText("count of passed students:");

    failStudentLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    failStudentLabel.setText("count of failed students:");

    passAverageLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    passAverageLabel.setText("average score without fail:");

    averageAnswerLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N

    studentAnswerLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N

    passStudentAnswerLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N

    failStudentAnswerLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N

    passAverageAnswerLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(courseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(courseField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(professorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(facultyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(133, 133, 133)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(averageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(passAverageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(failStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(studentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(passStudentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(averageAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passStudentAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(failStudentAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passAverageAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(183, 183, 183))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(courseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(courseField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addGap(26, 26, 26)
                                                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addGap(40, 40, 40)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(averageAnswerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                    .addComponent(averageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGap(49, 49, 49)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(studentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(studentAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passStudentAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(63, 63, 63)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(professorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(failStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(failStudentAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(65, 65, 65)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(facultyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passAverageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passAverageAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(67, 67, 67)
                            .addComponent(gradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(133, Short.MAX_VALUE))
    );
  }// </editor-fold>

  private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {
    try {
      Integer.parseInt(courseField.getText());
    } catch (Exception e) {
      mainFrame.showMessage("course id must be a number");
      client.changePanel(PanelName.COURSE_SUMMARY_PANEL, null);
      return;
    }

    client.searchCourseSummary(this, courseField.getText());
    courseField.setText("");
  }

  public void update(String id, String name, String professor, String faculty, String grade, String averageScore,
                     String studentCount, String passedStudentCount, String failStudentCount, String averageScoreWithoutFail) {
    idLabel.setText("id: " + id);
    nameLabel.setText("name: " + name);
    gradeLabel.setText("grade: " + grade);
    professorLabel.setText("professor: " + professor);
    facultyLabel.setText("faculty: " + faculty);

    averageAnswerLabel.setText(averageScore);
    studentAnswerLabel.setText(studentCount);
    passStudentAnswerLabel.setText(passedStudentCount);
    failStudentAnswerLabel.setText(failStudentCount);
    passAverageAnswerLabel.setText(averageScoreWithoutFail);
  }

  // Variables declaration - do not modify
  private javax.swing.JLabel averageAnswerLabel;
  private javax.swing.JLabel averageLabel;
  private javax.swing.JTextField courseField;
  private javax.swing.JLabel courseLabel;
  private javax.swing.JLabel facultyLabel;
  private javax.swing.JLabel failStudentAnswerLabel;
  private javax.swing.JLabel failStudentLabel;
  private javax.swing.JLabel gradeLabel;
  private javax.swing.JLabel idLabel;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JLabel passAverageAnswerLabel;
  private javax.swing.JLabel passAverageLabel;
  private javax.swing.JLabel passStudentAnswerLabel;
  private javax.swing.JLabel passStudentLabel;
  private javax.swing.JLabel professorLabel;
  private javax.swing.JButton searchButton;
  private javax.swing.JLabel studentAnswerLabel;
  private javax.swing.JLabel studentLabel;
  // End of variables declaration
}
