package GUI.student;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import client.Client;

/**
 *
 * @author HP
 */
public class EnrollmentCertificatePanel extends javax.swing.JPanel {
  Client client;

  /**
   * Creates new form EnrollmentCertificatePanel
   */
  public EnrollmentCertificatePanel(Client client) {
    this.client = client;
    setBounds(200, 270, 1100, 700);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    certificateArea = new javax.swing.JTextArea();
    jScrollPane1 = new javax.swing.JScrollPane();
    requestButton = new javax.swing.JButton();

    requestButton.setText("request enrollment certificate");
    requestButton.addActionListener(this::requestButtonActionPerformed);

    certificateArea.setColumns(20);
    certificateArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    certificateArea.setLineWrap(true);
    certificateArea.setRows(3);
    certificateArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    certificateArea.setEditable(false);
    certificateArea.setWrapStyleWord(true);
    jScrollPane1.setViewportView(certificateArea);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(407, 407, 407)
                                            .addComponent(requestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(304, 304, 304)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(310, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap(304, Short.MAX_VALUE)
                            .addComponent(requestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(190, 190, 190))
    );
  }// </editor-fold>

  private void requestButtonActionPerformed(java.awt.event.ActionEvent evt) {
    if (certificateArea.getText().equals("")) {
      client.enrollmentCertificate(this);
    }
  }

  public void update(String certification) {
    certificateArea.append(certification);
  }

  // Variables declaration - do not modify
  private javax.swing.JTextArea certificateArea;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JButton requestButton;
  // End of variables declaration
}
