package shared.request;

public enum RequestType {
  LOGIN,
  UPDATE,
  CHANGE_PHONE_NUMBER,
  CHANGE_EMAIL,
  IS_DEAN,
  ADD_TEMPORARY_SCORE_BY_STUDENT,
  ADD_TEMPORARY_SCORE_BY_PROFESSOR,
  ADD_SCORE,
  GET_RECOMMENDATION_RESULT,
  ENROLLMENT_CERTIFICATION,
  MINOR_REQUEST,
  DROPOUT_REQUEST,
  DORMITORY_REQUEST,
  DEFENDING_REQUEST,
  ANSWER_RECOMMENDATION
}
