package shared.request;

public enum RequestType {
  LOGIN,
  UPDATE,
  CHANGE_PHONE_NUMBER,
  CHANGE_EMAIL,
  IS_DEAN,
  ADD_TEMPORARY_SCORE,
  GET_RECOMMENDATION_RESULT,
  ENROLLMENT_CERTIFICATION,
  MINOR_REQUEST
}
