package client.GUI.professors.eduAssistant;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import client.GUI.MainFrame;
import client.Client;
import shared.model.PanelName;
import shared.util.Config;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author HP
 */
public class EduEducationalPanel extends javax.swing.JPanel {
  MainFrame mainFrame;
  Client client;
  JPanel jPanel;

  /**
   * Creates new form EduEducationalPanel
   */
  public EduEducationalPanel(MainFrame mainFrame, Client client) {
    this.client = client;
    this.mainFrame = mainFrame;
    setBounds(getConfig().getProperty(Integer.class, "eduEducationalPanelX"), getConfig().getProperty(Integer.class, "panelY"),
            getConfig().getProperty(Integer.class, "eduEducationalPanelWidth"), getConfig().getProperty(Integer.class, "panelHeight"));

    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    idLabel = new javax.swing.JLabel();
    idField = new javax.swing.JTextField();
    nameLabel = new javax.swing.JLabel();
    nameField = new javax.swing.JTextField();
    nameSearchButton = new javax.swing.JButton();
    idSearchButton = new javax.swing.JButton();

    idLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    idLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    idLabel.setText(getConfig().getProperty(String.class, "idLabelText"));

    idField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    nameLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    nameLabel.setText(getConfig().getProperty(String.class, "nameLabelText1"));

    nameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    nameSearchButton.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    nameSearchButton.setText(getConfig().getProperty(String.class, "nameSearchButtonText"));
    nameSearchButton.addActionListener(this::nameSearchButtonActionPerformed);

    idSearchButton.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    idSearchButton.setText(getConfig().getProperty(String.class, "idSearchButtonText"));
    idSearchButton.addActionListener(this::idSearchButtonActionPerformed);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(21, 21, 21))
                                    .addComponent(idSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(843, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(143, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addComponent(nameSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(78, 78, 78)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addComponent(idSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(248, 248, 248))
    );
  }// </editor-fold>

  private void nameSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {
    client.searchStudentStatusByName(this, nameField.getText());
  }

  private void idSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {
    try {
      Integer.parseInt(idField.getText());
    } catch (Exception e) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "idNumErrorMessage"));
      client.changePanel(PanelName.EDU_EDUCATIONAL_PANEL, null);
      return;
    }
    client.searchStudentStatusById(this, idField.getText());
  }

  public void update(JPanel jPanel, String id, String name) {
    if (this.jPanel != null) {
      this.remove(this.jPanel);
    }
    this.jPanel = jPanel;
    this.add(jPanel);
    idField.setText(id);
    nameField.setText(name);
  }

  private Config getConfig() {
    return Config.getConfig(Config.getMainConfig().getProperty(String.class, "eduAssistantConfig"));
  }

  // Variables declaration - do not modify
  private javax.swing.JTextField idField;
  private javax.swing.JLabel idLabel;
  private javax.swing.JButton idSearchButton;
  private javax.swing.JTextField nameField;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JButton nameSearchButton;
  // End of variables declaration
}
