package client.GUI.professors.eduAssistant;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import client.Client;
import client.GUI.MainFrame;
import shared.model.users.Student;
import shared.util.Config;
import shared.util.Time;

import java.awt.*;
import java.util.Date;
import java.util.Objects;

/**
 *
 * @author HP
 */
public class SetTakeCourseTimePanel extends javax.swing.JPanel {
  MainFrame mainFrame;
  Client client;

  /**
   * Creates new form SetTakeCourseTimePanel
   */
  public SetTakeCourseTimePanel(MainFrame mainFrame, Client client) {
    this.client = client;
    this.mainFrame = mainFrame;
    setBounds(getConfig().getProperty(Integer.class, "panelX"), getConfig().getProperty(Integer.class, "panelY"),
            getConfig().getProperty(Integer.class, "panelWidth"), getConfig().getProperty(Integer.class, "panelHeight"));
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    facultyBox = new javax.swing.JComboBox<>();
    gradeLabel = new javax.swing.JLabel();
    gradeBox = new javax.swing.JComboBox<>();
    enteringYearBox = new javax.swing.JCheckBox();
    enteringYearField = new javax.swing.JTextField();
    facultyLabel = new javax.swing.JLabel();
    startTakeCourseMinuteField = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    startTakeCourseMonthField = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    startTakeCourseDayField = new javax.swing.JTextField();
    startTakeCourseTimeLabel = new javax.swing.JLabel();
    startTakeCourseHourField = new javax.swing.JTextField();
    startTakeCourseYearField = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    startTakeCourseDateLabel = new javax.swing.JLabel();
    endTakeCourseDateLabel = new javax.swing.JLabel();
    endTakeCourseMinuteField = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    endTakeCourseMonthField = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    endTakeCourseDayField = new javax.swing.JTextField();
    endTakeCourseTimeLabel = new javax.swing.JLabel();
    endTakeCourseHourField = new javax.swing.JTextField();
    endTakeCourseYearField = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    setButton = new javax.swing.JButton();

    gradeLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    gradeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    gradeLabel.setText(getConfig().getProperty(String.class, "gradeLabelText1"));

    gradeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {getConfig().getProperty(String.class, "comboBoxDefault"),
            Student.Grade.underGraduate.toString(), Student.Grade.masters.toString(), Student.Grade.phd.toString()}));

    enteringYearBox.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    enteringYearBox.setText(getConfig().getProperty(String.class, "enteringYearBoxText"));

    enteringYearField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    facultyLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    facultyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    facultyLabel.setText(getConfig().getProperty(String.class, "facultyLabelText1"));

    startTakeCourseMinuteField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    jLabel1.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    jLabel1.setText("/");

    startTakeCourseMonthField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    jLabel2.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    jLabel2.setText("/");

    startTakeCourseDayField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    startTakeCourseTimeLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    startTakeCourseTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    startTakeCourseTimeLabel.setText(getConfig().getProperty(String.class, "startTakeCourseTimeLabelText"));

    startTakeCourseHourField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    startTakeCourseYearField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    jLabel3.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    jLabel3.setText(":");

    startTakeCourseDateLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    startTakeCourseDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    startTakeCourseDateLabel.setText(getConfig().getProperty(String.class, "startTakeCourseDateLabelText"));

    endTakeCourseDateLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    endTakeCourseDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    endTakeCourseDateLabel.setText(getConfig().getProperty(String.class, "endTakeCourseDateLabelText"));

    endTakeCourseMinuteField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    jLabel4.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    jLabel4.setText("/");

    endTakeCourseMonthField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    jLabel5.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    jLabel5.setText("/");

    endTakeCourseDayField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    endTakeCourseTimeLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    endTakeCourseTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    endTakeCourseTimeLabel.setText(getConfig().getProperty(String.class, "endTakeCourseTimeLabelText"));

    endTakeCourseHourField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    endTakeCourseYearField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    jLabel6.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
    jLabel6.setText(":");

    setButton.setText(getConfig().getProperty(String.class, "setButtonText"));
    setButton.addActionListener(this::setButtonActionPerformed);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(356, 356, 356)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(gradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(facultyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(gradeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(facultyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(13, 13, 13))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(enteringYearBox)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(enteringYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(startTakeCourseTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                    .addComponent(startTakeCourseDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(startTakeCourseYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(startTakeCourseMonthField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(startTakeCourseDayField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(startTakeCourseHourField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(startTakeCourseMinuteField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(endTakeCourseTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(endTakeCourseDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(endTakeCourseYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(endTakeCourseMonthField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(endTakeCourseDayField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(endTakeCourseHourField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(endTakeCourseMinuteField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(216, 216, 216))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(facultyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(facultyBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gradeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(enteringYearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enteringYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(106, 106, 106)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(startTakeCourseDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(startTakeCourseYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(startTakeCourseMonthField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(startTakeCourseDayField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(75, 75, 75)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(startTakeCourseTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(startTakeCourseHourField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(startTakeCourseMinuteField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(endTakeCourseDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(endTakeCourseYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(endTakeCourseMonthField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(endTakeCourseDayField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(75, 75, 75)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(endTakeCourseTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(endTakeCourseHourField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(endTakeCourseMinuteField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(58, 58, 58)
                            .addComponent(setButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(86, 86, 86))
    );
  }// </editor-fold>

  private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {
    if (startTakeCourseYearField.getText().equals("")) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "emptyStartTakeCourseTimeErrorMessage"));
      return;
    }
    if (startTakeCourseMonthField.getText().equals("")) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "emptyStartTakeCourseTimeErrorMessage"));
      return;
    }
    if (startTakeCourseDayField.getText().equals("")) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "emptyStartTakeCourseTimeErrorMessage"));
      return;
    }
    if (startTakeCourseHourField.getText().equals("")) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "emptyStartTakeCourseTimeErrorMessage"));
      return;
    }
    if (startTakeCourseMinuteField.getText().equals("")) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "emptyStartTakeCourseTimeErrorMessage"));
      return;
    }
    try {
      Integer.parseInt(startTakeCourseYearField.getText());
      Integer.parseInt(startTakeCourseMonthField.getText());
      Integer.parseInt(startTakeCourseDayField.getText());
      Integer.parseInt(startTakeCourseHourField.getText());
      Integer.parseInt(startTakeCourseMinuteField.getText());
    } catch (Exception e) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "startTakeCourseTimeNumErrorMessage"));
      return;
    }
    if (Integer.parseInt(startTakeCourseMonthField.getText())<0 || Integer.parseInt(startTakeCourseMonthField.getText())>12) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "invalidStartTakeCourseTimeErrorMessage"));
      return;
    }
    if (Integer.parseInt(startTakeCourseDayField.getText())<0 || Integer.parseInt(startTakeCourseDayField.getText())>31) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "invalidStartTakeCourseTimeErrorMessage"));
      return;
    }
    if (Integer.parseInt(startTakeCourseHourField.getText())<0 || Integer.parseInt(startTakeCourseHourField.getText())>23) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "invalidStartTakeCourseTimeErrorMessage"));
      return;
    }
    if (Integer.parseInt(startTakeCourseMinuteField.getText())<0 || Integer.parseInt(startTakeCourseMinuteField.getText())>59) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "invalidStartTakeCourseTimeErrorMessage"));
      return;
    }
    Date startTakeCourseDate;
    try {
      startTakeCourseDate = Time.convertStringToDateExam(startTakeCourseYearField.getText() + "/" + startTakeCourseMonthField.getText() + "/" +
              startTakeCourseDayField.getText() + " " + startTakeCourseHourField.getText() + ":" + startTakeCourseMinuteField.getText());
    } catch (Exception e) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "invalidStartTakeCourseTimeErrorMessage"));
      return;
    }

    if (endTakeCourseYearField.getText().equals("")) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "emptyEndTakeCourseTimeErrorMessage"));
      return;
    }
    if (endTakeCourseMonthField.getText().equals("")) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "emptyEndTakeCourseTimeErrorMessage"));
      return;
    }
    if (endTakeCourseDayField.getText().equals("")) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "emptyEndTakeCourseTimeErrorMessage"));
      return;
    }
    if (endTakeCourseHourField.getText().equals("")) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "emptyEndTakeCourseTimeErrorMessage"));
      return;
    }
    if (endTakeCourseMinuteField.getText().equals("")) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "emptyEndTakeCourseTimeErrorMessage"));
      return;
    }
    try {
      Integer.parseInt(endTakeCourseYearField.getText());
      Integer.parseInt(endTakeCourseMonthField.getText());
      Integer.parseInt(endTakeCourseDayField.getText());
      Integer.parseInt(endTakeCourseHourField.getText());
      Integer.parseInt(endTakeCourseMinuteField.getText());
    } catch (Exception e) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "endTakeCourseTimeNumErrorMessage"));
      return;
    }
    if (Integer.parseInt(endTakeCourseMonthField.getText())<0 || Integer.parseInt(endTakeCourseMonthField.getText())>12) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "invalidEndTakeCourseTimeErrorMessage"));
      return;
    }
    if (Integer.parseInt(endTakeCourseDayField.getText())<0 || Integer.parseInt(endTakeCourseDayField.getText())>31) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "invalidEndTakeCourseTimeErrorMessage"));
      return;
    }
    if (Integer.parseInt(endTakeCourseHourField.getText())<0 || Integer.parseInt(endTakeCourseHourField.getText())>23) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "invalidEndTakeCourseTimeErrorMessage"));
      return;
    }
    if (Integer.parseInt(endTakeCourseMinuteField.getText())<0 || Integer.parseInt(endTakeCourseMinuteField.getText())>59) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "invalidEndTakeCourseTimeErrorMessage"));
      return;
    }
    Date endTakeCourseDate;
    try {
      endTakeCourseDate = Time.convertStringToDateExam(endTakeCourseYearField.getText() + "/" + endTakeCourseMonthField.getText() + "/" +
              endTakeCourseDayField.getText() + " " + endTakeCourseHourField.getText() + ":" + endTakeCourseMinuteField.getText());
    } catch (Exception e) {
      mainFrame.showMessage(getConfig().getProperty(String.class, "invalidEndTakeCourseTimeErrorMessage"));
      return;
    }

    String enteringYear = "";
    if (enteringYearBox.isSelected()) {
      enteringYear = enteringYearField.getText();
      try {
        Integer.parseInt(enteringYear);
      } catch (Exception e) {
        return;
      }
    }

    client.setTakeCourseTime(Objects.requireNonNull(facultyBox.getSelectedItem()).toString(),
            Objects.requireNonNull(gradeBox.getSelectedItem()).toString(), enteringYear,
            Time.convertDateToStringExam(startTakeCourseDate), Time.convertDateToStringExam(endTakeCourseDate));
  }

  public void update(String[] faculties) {
    facultyBox.setModel(new javax.swing.DefaultComboBoxModel<>(faculties));
  }

  private Config getConfig() {
    return Config.getConfig(Config.getMainConfig().getProperty(String.class, "eduAssistantConfig"));
  }

  // Variables declaration - do not modify
  private javax.swing.JLabel endTakeCourseDateLabel;
  private javax.swing.JTextField endTakeCourseDayField;
  private javax.swing.JTextField endTakeCourseHourField;
  private javax.swing.JTextField endTakeCourseMinuteField;
  private javax.swing.JTextField endTakeCourseMonthField;
  private javax.swing.JLabel endTakeCourseTimeLabel;
  private javax.swing.JTextField endTakeCourseYearField;
  private javax.swing.JCheckBox enteringYearBox;
  private javax.swing.JTextField enteringYearField;
  private javax.swing.JComboBox<String> facultyBox;
  private javax.swing.JLabel facultyLabel;
  private javax.swing.JComboBox<String> gradeBox;
  private javax.swing.JLabel gradeLabel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JButton setButton;
  private javax.swing.JLabel startTakeCourseDateLabel;
  private javax.swing.JTextField startTakeCourseDayField;
  private javax.swing.JTextField startTakeCourseHourField;
  private javax.swing.JTextField startTakeCourseMinuteField;
  private javax.swing.JTextField startTakeCourseMonthField;
  private javax.swing.JLabel startTakeCourseTimeLabel;
  private javax.swing.JTextField startTakeCourseYearField;
  // End of variables declaration
}
