package client.GUI.mrMohseni;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import client.Client;
import shared.util.Config;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author HP
 */
public class SearchStudentPanel extends javax.swing.JPanel {
  Client client;

  /**
   * Creates new form SearchStudentPanel
   */
  public SearchStudentPanel(Client client) {
    this.client = client;
    setBounds(getConfig().getProperty(Integer.class, "panelX"), getConfig().getProperty(Integer.class, "panelY"),
            getConfig().getProperty(Integer.class, "panelWidth"), getConfig().getProperty(Integer.class, "panelHeight"));
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    searchLabel = new javax.swing.JLabel();
    searchField = new javax.swing.JTextField();
    studentTable = new javax.swing.JTable();

    studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
    ));
    studentTable.setCellSelectionEnabled(true);
    jScrollPane1.setViewportView(studentTable);
    studentTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
    studentTable.setModel(new DefaultTableModel() {
      @Override
      public boolean isCellEditable(int row, int column) {
        return false;
      }
    });

    searchLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 20)); // NOI18N
    searchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    searchLabel.setText(getConfig().getProperty(String.class, "searchLabelText"));

    searchField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    studentTable.addMouseListener(new MouseAdapter() {
      public void mouseClicked(MouseEvent e) {
        JTable jTable = (JTable) e.getSource();
        String studentId = (String) studentTable.getModel().getValueAt(jTable.getSelectedRow(), 0);
        client.changeToStudentPanelMrMohseni(studentId);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(234, 234, 234)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(300, 300, 300)
                                            .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(147, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchField, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                            .addGap(40, 40, 40)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(52, Short.MAX_VALUE))
    );
  }// </editor-fold>

  private void showData(String[][] data) {
    DefaultTableModel model = (DefaultTableModel) studentTable.getModel();
    String[] cols = {"id", "name", "faculty", "grade"};
    model.setDataVector(data, cols);
  }

  public void update(String[][] data) {
    showData(data);
  }

  public String getSearchString() {
    return searchField.getText();
  }

  private Config getConfig() {
    return Config.getConfig(Config.getMainConfig().getProperty(String.class, "mrMohseniConfig"));
  }

  // Variables declaration - do not modify
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField searchField;
  private javax.swing.JLabel searchLabel;
  private javax.swing.JTable studentTable;
  // End of variables declaration
}
