package client.GUI.messenger;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import client.Client;
import client.GUI.MainFrame;
import shared.model.users.UserRole;

import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author HP
 */
public class CreateChatPanel extends javax.swing.JPanel {
  MainFrame mainFrame;
  Client client;
  UserRole userRole;

  /**
   * Creates new form CreateChatPanel
   */
  public CreateChatPanel(MainFrame mainFrame, Client client, UserRole userRole) {
    this.client = client;
    this.mainFrame = mainFrame;
    this.userRole = userRole;
    setBounds(200, 270, 1100, 700);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {
    chatsButton = new javax.swing.JButton();
    addContactLabel = new javax.swing.JLabel();
    contactsLabel = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    contactIdLabel = new javax.swing.JLabel();
    contactIdField = new javax.swing.JTextField();
    addContactButton = new javax.swing.JButton();
    sendToAllBox = new javax.swing.JCheckBox();
    textField = new javax.swing.JTextField();
    sendTextButton = new javax.swing.JButton();
    sendFileButton = new javax.swing.JButton();
    contactsTable = new javax.swing.JTable();

    contactsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
    ));
    contactsTable.setCellSelectionEnabled(true);
    contactsTable.setModel(new DefaultTableModel() {
      @Override
      public boolean isCellEditable(int row, int column) {
        return false;
      }
    });
    jScrollPane1.setViewportView(contactsTable);

    chatsButton.setText("chats");

    addContactLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 22)); // NOI18N
    addContactLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    addContactLabel.setText("add contact");

    contactsLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 22)); // NOI18N
    contactsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    contactsLabel.setText("contacts");

    contactIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    contactIdLabel.setText("contact id:");

    contactIdField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    addContactButton.setText("add contact");

    sendToAllBox.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 20)); // NOI18N
    sendToAllBox.setText("send to all contacts");

    sendTextButton.setText("send text");
    sendTextButton.addActionListener(this::sendTextButtonActionPerformed);

    sendFileButton.setText("send file");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addGap(0, 0, Short.MAX_VALUE)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                            .addGap(71, 71, 71)
                                                                            .addComponent(addContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(addContactButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addGroup(layout.createSequentialGroup()
                                                                                    .addComponent(contactIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                    .addGap(43, 43, 43)
                                                                                    .addComponent(contactIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                    .addGap(37, 37, 37))))
                                                            .addGap(100, 100, 100))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(sendFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                    .addComponent(sendTextButton))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(sendToAllBox, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(contactsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(132, 132, 132))
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(chatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(875, 875, 875)))
                            .addGap(47, 47, 47))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(chatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(contactsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(addContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(contactIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(contactIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(addContactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(220, 220, 220)
                                            .addComponent(sendToAllBox, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(textField)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(sendTextButton)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(sendFileButton))))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(42, Short.MAX_VALUE))
    );
  }// </editor-fold>

  private void sendTextButtonActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  public void showData(Object[][] data) {
    String[] cols = {"id", "name", "faculty", "send message"};
    DefaultTableModel model = new DefaultTableModel(new String[]{}, data.length) {
      @Override public Class getColumnClass(int columnIndex) {
        if (columnIndex == 3) {
          return Boolean.class;
        }
        return String.class;
      }
    };
    model.setDataVector(data, cols);
    contactsTable.setModel(model);
  }

  public Boolean[] getSendMessageBooleans() {
    Boolean[] sendMessageBooleans = new Boolean[contactsTable.getRowCount()];
    for (int i = 0; i < contactsTable.getRowCount(); i++) {
      sendMessageBooleans[i] = (Boolean) contactsTable.getValueAt(i, 3);
    }
    return sendMessageBooleans;
  }

  public void update(Object[][] data) {
    showData(data);
  }

  // Variables declaration - do not modify
  private javax.swing.JButton addContactButton;
  private javax.swing.JLabel addContactLabel;
  private javax.swing.JButton chatsButton;
  private javax.swing.JTextField contactIdField;
  private javax.swing.JLabel contactIdLabel;
  private javax.swing.JLabel contactsLabel;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JButton sendFileButton;
  private javax.swing.JButton sendTextButton;
  private javax.swing.JCheckBox sendToAllBox;
  private javax.swing.JTextField textField;
  private javax.swing.JTable contactsTable;
  // End of variables declaration
}
